CMD_HEARTBEAT = bytes("HEARTBEAT", encoding='ascii')
CMD_OPEN_BEAM = bytes("OPEN BEAM", encoding='ascii')
CMD_CLOSE_BEAM = bytes("CLOSE BEAM", encoding='ascii')
CMD_SHUTDOWN_BOARD = bytes("SHUTDOWN BOARD", encoding='ascii')

DATA_CHUNK_SIZE = 128 << 10
SEP = "\\SEP\\"
CMD_DOWNLOAD_FILE = bytes(f"DOWNLOAD FILE{SEP}", encoding='ascii')

MiB = 1000 * 1000

UPLOAD_SPEED = 50 * MiB
DATA_CHUNKS_PER_SEC = UPLOAD_SPEED / DATA_CHUNK_SIZE
DELAY_EVERY_N_CHUNKS = 50
TIME_BETWEEN_DATA_CHUNKS = DELAY_EVERY_N_CHUNKS / DATA_CHUNKS_PER_SEC
